#!/bin/bash


if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo -ne '¯\\_(ツ)_/¯' | xclip -selection clipboard;
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo -ne '¯\\_(ツ)_/¯' | pbcopy;
fi


while getopts "rm" OPTION
do
    case $OPTION in
        r)  
            if [[ "$OSTYPE" == "linux-gnu" ]]; then
            	echo -ne '¯\\\\\\_(ツ)_/¯' | xclip -selection clipboard;
            elif [[ "$OSTYPE" == "darwin"* ]]; then
            	echo -ne '¯\\\\\\_(ツ)_/¯' | pbcopy;
            fi  
	    ;;
        m)  
            if [[ "$OSTYPE" == "linux-gnu" ]]; then
            	echo -ne '¯\\\_(ツ)\_/¯' | xclip -selection clipboard;
            elif [[ "$OSTYPE" == "darwin"* ]]; then
            	echo -ne '¯\\\_(ツ)\_/¯' | pbcopy;
            fi  
	    ;;

    esac
done

