#!/bin/bash
while getopts "r" OPTION
do
    case $OPTION in
        r)
            if [[ "$OSTYPE" == "linux-gnu" ]]; then
            	echo -ne '¯\\\\\\_(ツ)_/¯' | xclip -selection clipboard;
            elif [[ "$OSTYPE" == "darwin*" ]]; then
            	echo -ne '¯\\\\\\_(ツ)_/¯' | pbcopy;
            fi  
	    ;;
    esac
done

if [[ "$OSTYPE" == "linux-gnu" ]]; then
	echo -ne '¯\\_(ツ)_/¯' | xclip -selection clipboard;
elif [[ "$OSTYPE" == "darwin*" ]]; then
	echo -ne '¯\\_(ツ)_/¯' | pbcopy;
fi

